import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/lib/font";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
